### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by ggggggggg** [ggggggggg/Mass2.jl#1]
- [x] all steps return something that workunits works on
- [x] cumulative timings
- [x] status output
- [ ] better cuts interface, type?
- [x] toJLD works with non-perpulse types
